from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class GOHPartPreset:
    key: str
    label: str
    display_name: str
    export_name: str
    description: str
    numbering: str = "increment"


@dataclass(frozen=True)
class GOHRolePreset:
    key: str
    label: str
    description: str
    name_suffix: str = ""
    helper_flag: str | None = None
    collection_name: str | None = None
    default_shape_2d: str | None = None
    sets_attach_bone: bool = False


GOH_PART_PRESETS: tuple[GOHPartPreset, ...] = (
    GOHPartPreset("generic", "Generic Part", "Part", "part", "Generic visual part with no old 3ds Max baggage."),
    GOHPartPreset("body", "Body", "Body", "body", "Main hull or chassis section."),
    GOHPartPreset("body_back", "body_back", "body_back", "body_back", "Rear body section used by GOH aircraft and split-hull templates."),
    GOHPartPreset("turret", "Turret", "Turret", "turret", "Turret or rotating upper structure."),
    GOHPartPreset("gun", "Gun", "Gun", "gun", "Main cannon or articulated weapon mesh."),
    GOHPartPreset("gun_rot", "Gun_rot", "Gun_rot", "gun_rot", "Rotation pivot for a gun assembly."),
    GOHPartPreset("mgun", "Mgun", "Mgun", "mgun", "Machine-gun assembly."),
    GOHPartPreset("mgun_rot", "Mgun_rot", "Mgun_rot", "mgun_rot", "Machine-gun rotation or elevation pivot."),
    GOHPartPreset("engine", "Engine", "Engine", "engine", "Engine or transmission housing."),
    GOHPartPreset("engine1", "engine1", "engine1", "engine1", "Numbered aircraft or multi-engine section."),
    GOHPartPreset("engine2", "engine2", "engine2", "engine2", "Numbered aircraft or multi-engine section."),
    GOHPartPreset("wheel", "Wheel", "Wheel", "wheel", "Wheel, bogie, or roller section."),
    GOHPartPreset("track", "Track", "Track", "track", "Track mesh or track-related subpart."),
    GOHPartPreset("part", "part", "part", "part", "Generic named component used by airborne and stuff templates."),
    GOHPartPreset("part_auto", "part1* (Auto)", "part1", "part1", "Auto-numbered detached/destructible part family used by damage scripts."),
    GOHPartPreset("fragment_auto", "fragment1* (Auto)", "fragment1", "fragment1", "Auto-numbered fragment helper family used by damage scripts."),
    GOHPartPreset("hatch", "Hatch", "Hatch", "hatch", "Door, hatch, or opening cover."),
    GOHPartPreset("headlight", "Headlight", "Headlight", "headlight", "Headlight or lamp assembly."),
    GOHPartPreset("ammo", "Ammo", "Ammo", "ammo", "Ammo rack, shell mesh, or ammunition box."),
    GOHPartPreset("fuel", "Fuel", "Fuel", "fuel", "Fuel tank or jerry-can part."),
    GOHPartPreset("decor", "Decor", "Decor", "decor", "Non-functional decorative visual mesh."),
    GOHPartPreset("armor", "Armor", "Armor", "armor", "Armor plate or shielded visual mesh."),
    GOHPartPreset("glass", "Glass", "Glass", "glass", "Window or glass mesh section."),
    GOHPartPreset("detail", "Detail", "Detail", "detail", "Small visual detail or miscellaneous mesh."),
    GOHPartPreset("mantlet", "Mantled", "Mantled", "mantled", "Mantlet or gun-shield housing."),
    GOHPartPreset("shield", "Shield", "Shield", "shield", "Generic shield section."),
    GOHPartPreset("shield_left", "Shield_Left", "Shield_Left", "shield_left", "Left shield collision or mesh section."),
    GOHPartPreset("shield_front", "Shield_Front", "Shield_Front", "shield_front", "Front shield collision or mesh section."),
    GOHPartPreset("shield_right", "Shield_Right", "Shield_Right", "shield_right", "Right shield collision or mesh section."),
    GOHPartPreset("wheel_l", "Wheell", "Wheell", "wheell", "Left-side wheel or wheel collision block."),
    GOHPartPreset("wheel_r", "Wheelr", "Wheelr", "wheelr", "Right-side wheel or wheel collision block."),
    GOHPartPreset("wheell1_auto", "wheell1* (Auto)", "wheell1", "wheell1", "Auto-numbered left wheel family used by GOH vehicle skeletons."),
    GOHPartPreset("wheelr1_auto", "wheelr1* (Auto)", "wheelr1", "wheelr1", "Auto-numbered right wheel family used by GOH vehicle skeletons."),
    GOHPartPreset("wheell_optional_auto", "wheell + 1.. (Auto)", "wheell", "wheell", "Left wheel family whose first helper has no numeric suffix.", "optional_first"),
    GOHPartPreset("wheelr_optional_auto", "wheelr + 1.. (Auto)", "wheelr", "wheelr", "Right wheel family whose first helper has no numeric suffix.", "optional_first"),
    GOHPartPreset("wheel_l_mixed_auto", "wheelL + 1.. (Auto)", "wheelL", "wheelL", "Mixed-case left cannon wheel family with optional first suffix.", "optional_first"),
    GOHPartPreset("wheel_r_mixed_auto", "wheelR + 1.. (Auto)", "wheelR", "wheelR", "Mixed-case right cannon wheel family with optional first suffix.", "optional_first"),
    GOHPartPreset("track_l", "TrackL", "TrackL", "trackl", "Left track mesh or collision block."),
    GOHPartPreset("track_r", "TrackR", "TrackR", "trackr", "Right track mesh or collision block."),
    GOHPartPreset("trackleft", "trackleft", "trackleft", "trackleft", "GOH tank damage/volume name for the left track."),
    GOHPartPreset("trackright", "trackright", "trackright", "trackright", "GOH tank damage/volume name for the right track."),
    GOHPartPreset("armor_l", "ArmorL", "ArmorL", "armorl", "Left armor collision block."),
    GOHPartPreset("armor_r", "ArmorR", "ArmorR", "armorr", "Right armor collision block."),
    GOHPartPreset("inventory", "Inventory", "Inventory", "inventory", "Inventory or stowage collision/helper block."),
    GOHPartPreset("ram", "Ram", "Ram", "ram", "Ramming collision/helper block."),
    GOHPartPreset("propeller", "propeller", "propeller", "propeller", "Aircraft or animated building propeller part."),
    GOHPartPreset("propeller1", "propeller1", "propeller1", "propeller1", "Numbered propeller part used by GOH templates."),
    GOHPartPreset("propeller2", "propeller2", "propeller2", "propeller2", "Numbered propeller part used by GOH templates."),
    GOHPartPreset("wingleft", "wingleft", "wingleft", "wingleft", "Left aircraft wing component."),
    GOHPartPreset("wingleft2", "wingleft2", "wingleft2", "wingleft2", "Secondary left aircraft wing component."),
    GOHPartPreset("wingleft_top", "wingleft_top", "wingleft_top", "wingleft_top", "Upper left aircraft wing component."),
    GOHPartPreset("wingleft2_top", "wingleft2_top", "wingleft2_top", "wingleft2_top", "Upper secondary left aircraft wing component."),
    GOHPartPreset("wingright", "wingright", "wingright", "wingright", "Right aircraft wing component."),
    GOHPartPreset("wingright2", "wingright2", "wingright2", "wingright2", "Secondary right aircraft wing component."),
    GOHPartPreset("wingright_top", "wingright_top", "wingright_top", "wingright_top", "Upper right aircraft wing component."),
    GOHPartPreset("wingright2_top", "wingright2_top", "wingright2_top", "wingright2_top", "Upper secondary right aircraft wing component."),
    GOHPartPreset("casing", "casing", "casing", "casing", "Casing or ejected shell part."),
    GOHPartPreset("stuff", "stuff", "stuff", "stuff", "Generic stuff collider / prop part."),
    GOHPartPreset("stuff_weapon", "stuff_weapon", "stuff_weapon", "stuff_weapon", "Weapon-like stuff or LOD prop part."),
    GOHPartPreset("part_small", "part_small", "part_small", "part_small", "Small detached or destructible part."),
    GOHPartPreset("part_big", "part_big", "part_big", "part_big", "Large detached or destructible part."),
    GOHPartPreset("grenade", "grenade", "grenade", "grenade", "Grenade-style stuff helper or prop part."),
    GOHPartPreset("mine", "mine", "mine", "mine", "Mine-style stuff helper or prop part."),
    GOHPartPreset("close", "Close", "Close", "close", "Obstacle helper for close / blocked zones."),
    GOHPartPreset("select", "Select", "Select", "select", "Selection or interaction helper zone."),
    GOHPartPreset("walk", "Walk", "Walk", "walk", "Area helper for walkable surfaces."),
    GOHPartPreset("trigger", "Trigger", "Trigger", "trigger", "Area helper used as a trigger zone."),
    GOHPartPreset("zone", "Zone", "Zone", "zone", "Generic named area zone."),
    GOHPartPreset("cover", "Cover", "Cover", "cover", "Obstacle or area helper for cover."),
    GOHPartPreset("block", "Block", "Block", "block", "Generic blocker helper."),
    GOHPartPreset("emit", "Emit1", "Emit1", "Emit1", "Crew / passenger emit marker."),
    GOHPartPreset("emit2", "Emit2", "Emit2", "Emit2", "Crew / passenger emit marker."),
    GOHPartPreset("emit3", "Emit3", "Emit3", "Emit3", "Crew / passenger emit marker."),
    GOHPartPreset("emit4", "Emit4", "Emit4", "Emit4", "Crew / passenger emit marker."),
    GOHPartPreset("emit_auto", "Emit* (Auto)", "Emit1", "Emit1", "Auto-numbered emit marker family used by the Max tool."),
    GOHPartPreset("emit_lower_auto", "emit1* (Auto)", "emit1", "emit1", "Auto-numbered lowercase emit marker family used by GOH entity files."),
    GOHPartPreset("emit0_lower_auto", "emit0* (Auto)", "emit0", "emit0", "Auto-numbered lowercase emit marker family starting at emit0."),
    GOHPartPreset("seat", "Seat00", "Seat00", "Seat00", "Seat / placer helper with padded numbering."),
    GOHPartPreset("seat01_auto", "seat01* (Auto)", "seat01", "seat01", "Auto-numbered zero-padded lowercase passenger seat family."),
    GOHPartPreset("seat1_auto", "seat1* (Auto)", "seat1", "seat1", "Auto-numbered lowercase passenger seat family."),
    GOHPartPreset("commander", "Commander", "Commander", "Commander", "Commander placement helper."),
    GOHPartPreset("driver", "Driver", "Driver", "Driver", "Driver placement helper."),
    GOHPartPreset("gunner", "Gunner", "Gunner", "Gunner", "Gunner placement helper."),
    GOHPartPreset("visor", "Visor", "Visor", "Visor", "Driver or sight helper without numbering."),
    GOHPartPreset("visor1", "Visor1", "Visor1", "Visor1", "Driver or turret-linked visor helper."),
    GOHPartPreset("visor2", "Visor2", "Visor2", "Visor2", "Secondary visor helper."),
    GOHPartPreset("pivot_front", "Pivot_Front", "Pivot_Front", "Pivot_Front", "Front pivot dummy."),
    GOHPartPreset("pivot_back", "Pivot_Back", "Pivot_Back", "Pivot_Back", "Rear pivot dummy."),
    GOHPartPreset("steerl", "SteerL", "SteerL", "SteerL", "Left steering dummy."),
    GOHPartPreset("steerr", "SteerR", "SteerR", "SteerR", "Right steering dummy."),
    GOHPartPreset("steerl_lower", "steerl", "steerl", "steerl", "Lowercase left steering dummy used by GOH skeletons."),
    GOHPartPreset("steerr_lower", "steerr", "steerr", "steerr", "Lowercase right steering dummy used by GOH skeletons."),
    GOHPartPreset("steerl_lower_auto", "steerl1* (Auto)", "steerl1", "steerl1", "Auto-numbered lowercase left steering dummy family."),
    GOHPartPreset("steerr_lower_auto", "steerr1* (Auto)", "steerr1", "steerr1", "Auto-numbered lowercase right steering dummy family."),
    GOHPartPreset("springl", "SpringL", "SpringL", "SpringL", "Left suspension spring dummy."),
    GOHPartPreset("springr", "SpringR", "SpringR", "SpringR", "Right suspension spring dummy."),
    GOHPartPreset("springl_lower", "springl", "springl", "springl", "Lowercase left suspension spring dummy used by GOH skeletons."),
    GOHPartPreset("springr_lower", "springr", "springr", "springr", "Lowercase right suspension spring dummy used by GOH skeletons."),
    GOHPartPreset("springl_lower_auto", "springl1* (Auto)", "springl1", "springl1", "Auto-numbered lowercase left spring dummy family."),
    GOHPartPreset("springr_lower_auto", "springr1* (Auto)", "springr1", "springr1", "Auto-numbered lowercase right spring dummy family."),
    GOHPartPreset("wheelsl", "WheelsL", "WheelsL", "WheelsL", "Left support-wheel dummy."),
    GOHPartPreset("wheelsr", "WheelsR", "WheelsR", "WheelsR", "Right support-wheel dummy."),
    GOHPartPreset("wheelsl_exact", "wheelsl", "wheelsl", "wheelsl", "Lowercase left support-wheel dummy used by GOH skeletons."),
    GOHPartPreset("wheelsr_exact", "wheelsr", "wheelsr", "wheelsr", "Lowercase right support-wheel dummy used by GOH skeletons."),
    GOHPartPreset("wheelsl_optional_auto", "wheelsl + 1.. (Auto)", "wheelsl", "wheelsl", "Left support-wheel family whose first helper has no numeric suffix.", "optional_first"),
    GOHPartPreset("wheelsr_optional_auto", "wheelsr + 1.. (Auto)", "wheelsr", "wheelsr", "Right support-wheel family whose first helper has no numeric suffix.", "optional_first"),
    GOHPartPreset("wheelsupport_l", "WheelSL", "WheelSL", "WheelSL", "Left small support wheel dummy."),
    GOHPartPreset("wheelsupport_r", "WheelSR", "WheelSR", "WheelSR", "Right small support wheel dummy."),
    GOHPartPreset("link1", "Link1", "Link1", "Link1", "Dummy link helper."),
    GOHPartPreset("link2", "Link2", "Link2", "Link2", "Second dummy link helper."),
    GOHPartPreset("support1", "Support1", "Support1", "Support1", "Support helper."),
    GOHPartPreset("support2", "Support2", "Support2", "Support2", "Support helper."),
    GOHPartPreset("support3", "Support3", "Support3", "Support3", "Support helper."),
    GOHPartPreset("handle", "Handle", "Handle", "Handle", "Handle helper used by some weapon templates."),
    GOHPartPreset("foresight1", "Foresight1", "Foresight1", "Foresight1", "Primary foresight / muzzle reference point."),
    GOHPartPreset("foresight3", "Foresight3", "Foresight3", "Foresight3", "Additional foresight marker."),
    GOHPartPreset("foresight4", "Foresight4", "Foresight4", "Foresight4", "MG or alternate foresight marker."),
    GOHPartPreset("foresight5", "Foresight5", "Foresight5", "Foresight5", "Additional foresight marker."),
    GOHPartPreset("foresight6", "Foresight6", "Foresight6", "Foresight6", "Additional foresight marker."),
    GOHPartPreset("fx_trace_l1", "fxTraceL1", "fxTraceL1", "fxTraceL1", "Left tracer effect marker."),
    GOHPartPreset("fx_trace_l2", "fxTraceL2", "fxTraceL2", "fxTraceL2", "Left tracer effect marker."),
    GOHPartPreset("fx_trace_r1", "fxTraceR1", "fxTraceR1", "fxTraceR1", "Right tracer effect marker."),
    GOHPartPreset("fx_trace_r2", "fxTraceR2", "fxTraceR2", "fxTraceR2", "Right tracer effect marker."),
    GOHPartPreset("fx_trace_game_l1", "FXtraceL1", "FXtraceL1", "FXtraceL1", "GOH script-case left track/tracer effect marker."),
    GOHPartPreset("fx_trace_game_r1", "FXtraceR1", "FXtraceR1", "FXtraceR1", "GOH script-case right track/tracer effect marker."),
    GOHPartPreset("fx_trace_game_m1", "FXtraceM1", "FXtraceM1", "FXtraceM1", "GOH script-case center track/tracer effect marker."),
    GOHPartPreset("fx_tracem1", "FXtracem1", "FXtracem1", "FXtracem1", "GOH script-case center aircraft tracer effect marker."),
    GOHPartPreset("fx_tracem2", "FXtracem2", "FXtracem2", "FXtracem2", "GOH script-case center aircraft tracer effect marker."),
    GOHPartPreset("fx_tracem3", "FXtracem3", "FXtracem3", "FXtracem3", "GOH script-case center aircraft tracer effect marker."),
    GOHPartPreset("fx_tracem4", "FXtracem4", "FXtracem4", "FXtracem4", "GOH script-case center aircraft tracer effect marker."),
    GOHPartPreset("fxtracel_auto", "fxtracel1* (Auto)", "fxtracel1", "fxtracel1", "Auto-numbered lowercase left trace marker family."),
    GOHPartPreset("fxtracer_auto", "fxtracer1* (Auto)", "fxtracer1", "fxtracer1", "Auto-numbered lowercase right trace marker family."),
    GOHPartPreset("fxtracem_auto", "fxtracem1* (Auto)", "fxtracem1", "fxtracem1", "Auto-numbered lowercase center trace marker family."),
    GOHPartPreset("fx_dust", "fxDust", "fxDust", "fxDust", "Dust effect marker."),
    GOHPartPreset("fx_light", "fxLight", "fxLight", "fxLight", "Light or flare effect marker."),
    GOHPartPreset("headlight_l", "HeadlightL", "HeadlightL", "HeadlightL", "Left headlight effect marker."),
    GOHPartPreset("headlight_r", "HeadlightR", "HeadlightR", "HeadlightR", "Right headlight effect marker."),
    GOHPartPreset("headlightl", "headlightl", "headlightl", "headlightl", "Lowercase left headlight marker used by vehicle scripts."),
    GOHPartPreset("headlightr", "headlightr", "headlightr", "headlightr", "Lowercase right headlight marker used by vehicle scripts."),
    GOHPartPreset("headlightc", "headlightc", "headlightc", "headlightc", "Lowercase center headlight marker used by vehicle scripts."),
    GOHPartPreset("armorlightl", "armorlightl", "armorlightl", "armorlightl", "Lowercase left armor light marker used by vehicle scripts."),
    GOHPartPreset("armorlightr", "armorlightr", "armorlightr", "armorlightr", "Lowercase right armor light marker used by vehicle scripts."),
    GOHPartPreset("dimlight", "dimlight", "dimlight", "dimlight", "Lowercase dim light marker used by vehicle scripts."),
    GOHPartPreset("dimlightl", "dimlightl", "dimlightl", "dimlightl", "Lowercase left dim light marker used by vehicle scripts."),
    GOHPartPreset("dimlightr", "dimlightr", "dimlightr", "dimlightr", "Lowercase right dim light marker used by vehicle scripts."),
    GOHPartPreset("fx_fire1", "fxFire1", "fxFire1", "fxFire1", "Fire effect marker."),
    GOHPartPreset("fx_fire2", "fxFire2", "fxFire2", "fxFire2", "Fire effect marker."),
    GOHPartPreset("fx_fire3", "fxFire3", "fxFire3", "fxFire3", "Fire effect marker."),
    GOHPartPreset("fx_smoke1", "fxSmoke1", "fxSmoke1", "fxSmoke1", "Smoke effect marker."),
    GOHPartPreset("fx_smoke2", "fxSmoke2", "fxSmoke2", "fxSmoke2", "Smoke effect marker."),
    GOHPartPreset("fxfire_auto", "fxfire1* (Auto)", "fxfire1", "fxfire1", "Auto-numbered lowercase fire marker family."),
    GOHPartPreset("fxsmoke_auto", "fxsmoke1* (Auto)", "fxsmoke1", "fxsmoke1", "Auto-numbered lowercase smoke marker family."),
    GOHPartPreset("fxfire_script_auto", "FXfire1* (Auto)", "FXfire1", "FXfire1", "Auto-numbered script-case fire marker family."),
    GOHPartPreset("fxsmoke_script_auto", "FXsmoke1* (Auto)", "FXsmoke1", "FXsmoke1", "Auto-numbered script-case smoke marker family."),
    GOHPartPreset("fx_stop1", "fxStop1", "fxStop1", "fxStop1", "Stop or brake effect marker."),
    GOHPartPreset("fx_stop2", "fxStop2", "fxStop2", "fxStop2", "Stop or brake effect marker."),
    GOHPartPreset("fx_shell1", "fxShell1", "fxShell1", "fxShell1", "Shell-eject effect marker."),
    GOHPartPreset("fx_invers", "fx_Invers", "fx_Invers", "fx_Invers", "Inverse / mirrored effect marker."),
    GOHPartPreset("fx_steam", "fxSteam", "fxSteam", "fxSteam", "Steam or vapor effect marker."),
    GOHPartPreset("fxshell", "FxShell", "FxShell", "FxShell", "Weapon shell or point helper used by the old Max weapon tool."),
    GOHPartPreset("carriage", "Carriage", "Carriage", "carriage", "Carriage or sidecar visual part."),
    GOHPartPreset("carriage1", "Carriage1", "Carriage1", "carriage1", "Primary cannon carriage part."),
    GOHPartPreset("carriage2", "Carriage2", "Carriage2", "carriage2", "Secondary cannon carriage part."),
    GOHPartPreset("cartridge_belt", "Cartridge_Belt", "Cartridge_Belt", "cartridge_belt", "Ammo belt or cartridge feed visual part."),
    GOHPartPreset("steerrudder", "SteerRudder", "SteerRudder", "steerrudder", "Car steering rudder or steering helper."),
    GOHPartPreset("steerl1", "SteerL1", "SteerL1", "SteerL1", "Left cannon steering dummy."),
    GOHPartPreset("steerr1", "SteerR1", "SteerR1", "SteerR1", "Right cannon steering dummy."),
    GOHPartPreset("springl2", "SpringL2", "SpringL2", "SpringL2", "Left cannon suspension helper."),
    GOHPartPreset("springr2", "SpringR2", "SpringR2", "SpringR2", "Right cannon suspension helper."),
    GOHPartPreset("standl", "StandL", "StandL", "standl", "Left stabilizer or stand part."),
    GOHPartPreset("standr", "StandR", "StandR", "standr", "Right stabilizer or stand part."),
    GOHPartPreset("shankl", "ShankL", "ShankL", "shankl", "Left stand shank or linkage part."),
    GOHPartPreset("shankr", "ShankR", "ShankR", "shankr", "Right stand shank or linkage part."),
    GOHPartPreset("stan1", "Stan1", "Stan1", "stan1", "Cannon stand visual mesh that often behaves like CommonMesh."),
    GOHPartPreset("stan2", "Stan2", "Stan2", "stan2", "Cannon stand visual mesh that often behaves like CommonMesh."),
    GOHPartPreset("stan3", "Stan3", "Stan3", "stan3", "Cannon stand visual mesh that often behaves like CommonMesh."),
)

GOH_PART_PRESET_MAP = {preset.key: preset for preset in GOH_PART_PRESETS}

GOH_ROLE_PART_KEYS: dict[str, tuple[str, ...]] = {
    "visual": (
        "generic",
        "body",
        "body_back",
        "turret",
        "gun",
        "gun_rot",
        "mgun",
        "mgun_rot",
        "engine",
        "engine1",
        "engine2",
        "wheel",
        "wheell1_auto",
        "wheelr1_auto",
        "wheell_optional_auto",
        "wheelr_optional_auto",
        "wheel_l_mixed_auto",
        "wheel_r_mixed_auto",
        "track",
        "part",
        "part_auto",
        "fragment_auto",
        "hatch",
        "headlight",
        "ammo",
        "fuel",
        "decor",
        "armor",
        "glass",
        "detail",
        "mantlet",
        "shield",
        "shield_left",
        "shield_front",
        "shield_right",
        "trackleft",
        "trackright",
        "propeller",
        "propeller1",
        "propeller2",
        "wingleft",
        "wingleft2",
        "wingleft_top",
        "wingleft2_top",
        "wingright",
        "wingright2",
        "wingright_top",
        "wingright2_top",
        "casing",
        "stuff",
        "stuff_weapon",
        "part_small",
        "part_big",
        "grenade",
        "mine",
    ),
    "attachment": (
        "generic",
        "emit",
        "emit2",
        "emit3",
        "emit4",
        "emit_auto",
        "emit_lower_auto",
        "emit0_lower_auto",
        "seat",
        "seat01_auto",
        "seat1_auto",
        "commander",
        "driver",
        "gunner",
        "visor",
        "visor1",
        "visor2",
        "pivot_front",
        "pivot_back",
        "steerl",
        "steerr",
        "steerl_lower",
        "steerr_lower",
        "steerl_lower_auto",
        "steerr_lower_auto",
        "springl",
        "springr",
        "springl_lower",
        "springr_lower",
        "springl_lower_auto",
        "springr_lower_auto",
        "wheelsl",
        "wheelsr",
        "wheelsl_exact",
        "wheelsr_exact",
        "wheelsl_optional_auto",
        "wheelsr_optional_auto",
        "wheelsupport_l",
        "wheelsupport_r",
        "link1",
        "link2",
        "support1",
        "support2",
        "support3",
        "handle",
    ),
    "volume": (
        "body",
        "body_back",
        "engine",
        "engine1",
        "engine2",
        "fuel",
        "turret",
        "gun",
        "wheel_l",
        "wheel_r",
        "wheell1_auto",
        "wheelr1_auto",
        "wheell_optional_auto",
        "wheelr_optional_auto",
        "wheel_l_mixed_auto",
        "wheel_r_mixed_auto",
        "track_l",
        "track_r",
        "trackleft",
        "trackright",
        "shield",
        "shield_left",
        "shield_front",
        "shield_right",
        "mantlet",
        "inventory",
        "ram",
        "armor_l",
        "armor_r",
        "part",
        "part_auto",
        "fragment_auto",
        "propeller",
        "wingleft",
        "wingright",
        "casing",
        "stuff",
        "part_small",
        "part_big",
        "detail",
        "generic",
    ),
    "obstacle": (
        "generic",
        "close",
        "select",
        "cover",
        "block",
        "body",
        "track",
        "decor",
    ),
    "area": (
        "generic",
        "walk",
        "trigger",
        "zone",
        "select",
        "cover",
        "body",
        "track",
    ),
    "fx": (
        "foresight1",
        "foresight3",
        "foresight4",
        "foresight5",
        "foresight6",
        "fx_trace_l1",
        "fx_trace_l2",
        "fx_trace_r1",
        "fx_trace_r2",
        "fx_trace_game_l1",
        "fx_trace_game_r1",
        "fx_trace_game_m1",
        "fx_tracem1",
        "fx_tracem2",
        "fx_tracem3",
        "fx_tracem4",
        "fxtracel_auto",
        "fxtracer_auto",
        "fxtracem_auto",
        "fx_dust",
        "fx_light",
        "headlight_l",
        "headlight_r",
        "headlightl",
        "headlightr",
        "headlightc",
        "armorlightl",
        "armorlightr",
        "dimlight",
        "dimlightl",
        "dimlightr",
        "fx_fire1",
        "fx_fire2",
        "fx_fire3",
        "fx_smoke1",
        "fx_smoke2",
        "fxfire_auto",
        "fxsmoke_auto",
        "fxfire_script_auto",
        "fxsmoke_script_auto",
        "fx_stop1",
        "fx_stop2",
        "fx_shell1",
        "fxshell",
        "fx_invers",
        "fx_steam",
    ),
}

GOH_TEMPLATE_FAMILY_ITEMS = (
    ("GENERIC", "Generic", "Show the full general-purpose GOH preset library"),
    ("TANK", "Tank", "Filter parts to the common tank-style MultiScript naming set"),
    ("CAR", "Car", "Filter parts to the common car / truck / motorcycle naming set"),
    ("CANNON", "Cannon", "Filter parts to the towed-gun / cannon naming set"),
    ("AIRCRAFT", "Aircraft", "Filter parts to GOH aircraft / airborne component and effect naming set"),
    ("STUFF", "Stuff / Prop", "Filter parts to generic stuff, casing, grenade, mine, and destructible prop naming"),
    ("WEAPON", "Weapon", "Filter parts to the old MultiScript weapon helper naming set"),
)

GOH_TEMPLATE_ROLE_PART_KEYS: dict[str, dict[str, tuple[str, ...]]] = {
    "GENERIC": GOH_ROLE_PART_KEYS,
    "TANK": {
        "visual": ("body", "engine", "turret", "gun_rot", "gun", "mgun", "mgun_rot", "ammo", "hatch", "detail", "mantlet", "part_auto"),
        "attachment": (
            "emit_auto",
            "emit_lower_auto",
            "emit0_lower_auto",
            "emit",
            "emit2",
            "emit3",
            "emit4",
            "seat",
            "seat01_auto",
            "seat1_auto",
            "commander",
            "driver",
            "gunner",
            "visor",
            "visor1",
            "visor2",
            "steerl_lower",
            "steerr_lower",
            "springl_lower",
            "springr_lower",
            "wheelsl_exact",
            "wheelsr_exact",
        ),
        "volume": (
            "body",
            "engine",
            "turret",
            "gun",
            "track_l",
            "track_r",
            "trackleft",
            "trackright",
            "wheell1_auto",
            "wheelr1_auto",
            "wheell_optional_auto",
            "wheelr_optional_auto",
            "mantlet",
            "inventory",
            "ram",
            "armor_l",
            "armor_r",
            "detail",
        ),
        "obstacle": ("close", "select", "cover", "body", "track"),
        "area": ("walk", "trigger", "zone", "select", "cover", "body", "track"),
        "fx": (
            "foresight1",
            "foresight3",
            "foresight4",
            "foresight5",
            "foresight6",
            "fx_trace_game_l1",
            "fx_trace_game_r1",
            "fx_trace_game_m1",
            "fxtracel_auto",
            "fxtracer_auto",
            "fx_dust",
            "fx_light",
            "headlightl",
            "headlightr",
            "headlightc",
            "fxfire_auto",
            "fxsmoke_auto",
            "fxfire_script_auto",
            "fxsmoke_script_auto",
            "fx_stop1",
            "fx_stop2",
        ),
    },
    "CAR": {
        "visual": ("body", "engine", "armor", "hatch", "wheel", "wheell1_auto", "wheelr1_auto", "glass", "fuel", "detail", "gun_rot", "gun", "mgun_rot", "mgun", "carriage", "steerrudder"),
        "attachment": (
            "emit_auto",
            "emit_lower_auto",
            "emit0_lower_auto",
            "emit",
            "emit2",
            "emit3",
            "emit4",
            "seat",
            "seat01_auto",
            "seat1_auto",
            "commander",
            "driver",
            "gunner",
            "visor",
            "visor1",
            "visor2",
            "pivot_front",
            "pivot_back",
            "steerl",
            "steerr",
            "steerl_lower",
            "steerr_lower",
            "steerl_lower_auto",
            "steerr_lower_auto",
            "springl",
            "springr",
            "springl_lower",
            "springr_lower",
            "springl_lower_auto",
            "springr_lower_auto",
            "wheelsl",
            "wheelsr",
            "wheelsl_exact",
            "wheelsr_exact",
            "wheelsl_optional_auto",
            "wheelsr_optional_auto",
        ),
        "volume": ("body", "engine", "armor", "wheel_l", "wheel_r", "wheell1_auto", "wheelr1_auto", "wheell_optional_auto", "wheelr_optional_auto", "glass", "fuel", "detail", "turret", "gun"),
        "obstacle": ("close", "select", "cover", "body"),
        "area": ("walk", "trigger", "zone", "select", "cover", "body"),
        "fx": ("fx_trace_game_l1", "fx_trace_game_r1", "fxtracel_auto", "fxtracer_auto", "fx_dust", "fx_light", "headlightl", "headlightr", "headlightc", "armorlightl", "armorlightr", "dimlight", "dimlightl", "dimlightr", "fxfire_auto", "fxsmoke_auto", "fx_stop1", "fx_stop2", "foresight1", "foresight3", "foresight4", "foresight5", "foresight6"),
    },
    "CANNON": {
        "visual": ("body", "turret", "shield_left", "shield_front", "shield_right", "shield", "gun_rot", "gun", "mgun_rot", "mgun", "carriage1", "carriage2", "cartridge_belt", "detail", "standl", "standr", "shankl", "shankr", "stan1", "stan2", "stan3", "part_auto", "fragment_auto"),
        "attachment": ("pivot_front", "pivot_back", "steerl1", "steerr1", "steerl_lower_auto", "steerr_lower_auto", "wheel_r", "wheel_l_mixed_auto", "wheel_r_mixed_auto", "springl2", "springr2", "springl_lower_auto", "springr_lower_auto", "link1", "link2", "support1", "support2", "support3", "seat", "seat01_auto", "commander", "driver", "gunner", "visor", "visor1", "visor2"),
        "volume": ("body", "engine", "fuel", "shield_left", "shield_front", "shield_right", "shield", "wheel_l", "wheel_r", "wheel_l_mixed_auto", "wheel_r_mixed_auto", "detail", "turret", "gun"),
        "obstacle": ("close", "select", "cover", "body"),
        "area": ("walk", "trigger", "zone", "body"),
        "fx": ("foresight1", "foresight3", "foresight4", "foresight5", "foresight6", "fx_trace_game_l1", "fx_trace_game_r1", "fxtracel_auto", "fxtracer_auto", "fx_dust", "fxfire_auto", "fxsmoke_auto", "fx_shell1", "fxshell", "fx_invers"),
    },
    "AIRCRAFT": {
        "visual": (
            "body",
            "body_back",
            "engine1",
            "engine2",
            "propeller",
            "propeller1",
            "propeller2",
            "wingleft",
            "wingleft2",
            "wingleft_top",
            "wingleft2_top",
            "wingright",
            "wingright2",
            "wingright_top",
            "wingright2_top",
            "wheel",
            "wheell1_auto",
            "wheelr1_auto",
            "part",
            "part_auto",
            "detail",
        ),
        "attachment": ("emit_lower_auto", "emit_auto", "emit", "emit2", "seat01_auto", "seat1_auto", "driver", "gunner", "commander", "visor", "pivot_front", "pivot_back"),
        "volume": ("body", "body_back", "engine1", "engine2", "propeller", "wingleft", "wingright", "wheel", "wheell1_auto", "wheelr1_auto", "part", "detail"),
        "obstacle": ("close", "select", "cover", "body", "part"),
        "area": ("walk", "trigger", "zone", "select", "body", "part"),
        "fx": ("fx_trace_game_l1", "fx_trace_game_r1", "fx_trace_game_m1", "fxtracel_auto", "fxtracer_auto", "fxtracem_auto", "fx_tracem1", "fx_tracem2", "fx_tracem3", "fx_tracem4", "fx_dust", "fx_light", "fxfire_auto", "fxsmoke_auto", "fxfire_script_auto", "fxsmoke_script_auto"),
    },
    "STUFF": {
        "visual": ("generic", "body", "part", "part_auto", "fragment_auto", "detail", "casing", "stuff", "stuff_weapon", "part_small", "part_big", "grenade", "mine", "ammo", "fuel", "decor"),
        "attachment": ("emit", "emit_auto", "emit_lower_auto", "emit0_lower_auto", "seat01_auto", "pivot_front", "pivot_back", "handle"),
        "volume": ("body", "part", "part_auto", "fragment_auto", "detail", "casing", "stuff", "part_small", "part_big", "grenade", "mine", "ammo", "fuel", "generic"),
        "obstacle": ("select", "cover", "block", "body", "part", "stuff"),
        "area": ("trigger", "zone", "select", "body", "part"),
        "fx": ("fx_light", "fxfire_auto", "fxsmoke_auto", "fxfire_script_auto", "fxsmoke_script_auto", "fx_shell1", "fxshell"),
    },
    "WEAPON": {
        "visual": ("generic", "body", "detail"),
        "attachment": ("handle",),
        "volume": ("body", "select", "generic"),
        "obstacle": ("select",),
        "area": ("trigger",),
        "fx": ("foresight3", "fxshell"),
    },
}

GOH_ROLE_PRESETS: tuple[GOHRolePreset, ...] = (
    GOHRolePreset("visual", "Visual Mesh", "Standard visible GOH mesh part."),
    GOHRolePreset(
        "attachment",
        "Dummy / Placer",
        "Named dummy, placer, or helper node that should explicitly attach to a GOH bone.",
        sets_attach_bone=True,
    ),
    GOHRolePreset(
        "volume",
        "Collision Volume",
        "3D collision volume helper. Links to GOH_VOLUMES and writes volume metadata.",
        name_suffix="_vol",
        helper_flag="goh_is_volume",
        collection_name="GOH_VOLUMES",
    ),
    GOHRolePreset(
        "obstacle",
        "Obstacle (2D)",
        "2D obstacle helper. Links to GOH_OBSTACLES and defaults to Obb2.",
        name_suffix="_obstacle",
        helper_flag="goh_is_obstacle",
        collection_name="GOH_OBSTACLES",
        default_shape_2d="obb2",
    ),
    GOHRolePreset(
        "area",
        "Area (2D)",
        "2D area helper. Links to GOH_AREAS and defaults to Polygon2.",
        name_suffix="_area",
        helper_flag="goh_is_area",
        collection_name="GOH_AREAS",
        default_shape_2d="polygon2",
    ),
    GOHRolePreset("fx", "Effect / Marker", "Named effect marker without collision/helper flags."),
)

GOH_ROLE_PRESET_MAP = {preset.key: preset for preset in GOH_ROLE_PRESETS}
GOH_ROLE_PRESET_ITEMS = [
    (preset.key, preset.label, preset.description)
    for preset in GOH_ROLE_PRESETS
]

GOH_HELPER_FLAGS = ("goh_is_volume", "goh_is_obstacle", "goh_is_area")
GOH_HELPER_COLLECTIONS = ("GOH_VOLUMES", "GOH_OBSTACLES", "GOH_AREAS")
GOH_TRANSLATION_CONTEXTS = ("*", "GOH_PRESET")
GOH_TRANSLATION_LOCALES = ("zh_CN", "zh_HANS", "zh_TW")
GOH_TRANSLATION_DOMAIN = f"{__package__ or __name__}.goh_en_labels"

GOH_LEGACY_TEXT_FALLBACKS: dict[str, tuple[str, ...]] = {
    "goh_attach_bone": ("bone", "attachbone", "parent"),
    "goh_bone_name": ("id",),
    "goh_bone_type": ("bonetype",),
    "goh_component": ("component",),
    "goh_shape_name": ("id", "name"),
    "goh_shape_2d": ("shape", "shape2d"),
    "goh_tags": ("tags",),
    "goh_transform_block": ("transform",),
    "goh_volume_bone": ("bone",),
    "goh_volume_name": ("id", "name"),
}

GOH_LEGACY_FLOAT_FALLBACKS: dict[str, tuple[str, ...]] = {
    "goh_density": ("density",),
    "goh_speed": ("ikspeed", "speed"),
}

GOH_LEGACY_INT_FALLBACKS: dict[str, tuple[str, ...]] = {
    "goh_layer": ("layer",),
    "goh_visibility": ("visibility",),
}

GOH_LEGACY_BOOL_FLAGS: dict[str, tuple[str, ...]] = {
    "goh_force_mesh_animation": ("commonmesh",),
    "goh_is_volume": ("volume",),
    "goh_lod_off": ("off", "lodlastoff"),
    "goh_no_cast_shadows": ("nocastshadows",),
    "goh_decal_target": ("decaltarget",),
    "goh_no_group_mesh": ("nogroupmesh",),
    "goh_no_get_shadows": ("nogetshadows",),
    "goh_ground": ("ground",),
    "goh_rotate_2d": ("rotate",),
    "goh_speed2": ("speed2",),
    "goh_terminator": ("terminator",),
}

GOH_CUSTOM_BOOL_ALIASES: dict[str, tuple[str, ...]] = {
    "goh_force_mesh_animation": ("goh_force_commonmesh",),
}


def _build_translation_overrides() -> dict[str, dict[tuple[str, str], str]]:
    msgids = {
        preset.label
        for preset in GOH_PART_PRESETS
    }
    msgids.update(preset.label for preset in GOH_ROLE_PRESETS)
    msgids.update(label for _key, label, _description in GOH_TEMPLATE_FAMILY_ITEMS)
    msgids.update(
        {
            "Poly",
            "CommonMesh",
            "Body_vol",
            "Select_vol",
            "Foresight3",
            "Handle",
            "FxShell",
            "Polyhedron (.vol)",
            "Primitive Box",
            "Primitive Sphere",
            "Primitive Cylinder",
            "X Axis",
            "Y Axis",
            "Z Axis",
            "Force",
            "Clear",
            "Leave",
            "Blender -> GOH (Legacy)",
            "None / GOH Native",
            "Auto / Match Imported Model",
            "Auto",
            "Orientation",
            "Matrix34",
            "Validation Scope",
            "Validate GOH Scene",
            "Auto-Fill GOH Materials",
            "Import GOH Model",
            "Assign LOD Files",
            "Volume From Bounds",
            "Create Recoil Action",
            "Assign Physics Link",
            "Bake Linked Recoil",
            "Bake Directional Set",
            "Bake Impact Response",
            "Create Armor Ripple",
            "Load Role Defaults",
            "Clear Physics Links",
            "Fire Trigger Volumes",
            "Create Fire Trigger Volumes",
            "Trigger Radius",
            "Trigger Thickness",
            "gun_recoil Distance",
            "Arc Segments",
            "Replace Existing",
            "LOD Levels",
            "Write OFF",
            "Helper Volume",
            "Recoil Axis",
            "Direction Set",
            "Clip Prefix",
            "Impact Clip",
            "Ripple Amplitude",
            "Ripple Radius",
            "Ripple Waves",
            "Physics Power",
            "Body Sway Strength",
            "Antenna Sway Strength",
            "Antenna Mount",
            "Antenna on Turret",
            "Antenna on Body",
            "Duration Scale",
            "Import Materials",
            "Load Diffuse Textures",
            "LOD0 Only",
            "Link Role",
            "Link Weight",
            "Create NLA Clips",
            "Clear Baked Actions",
            "Body Spring",
            "Antenna Whip",
            "Accessory Jitter",
            "Follower",
            "Suspension Bounce",
            "Track Rumble",
            "Use Stored Links",
            "Four Fire Directions",
            "Eight Fire Directions",
            "Local +X",
            "Local -X",
            "Local +Y",
            "Local -Y",
            "Local +Z",
            "Local -Z",
        }
    )
    translations: dict[str, dict[tuple[str, str], str]] = {}
    for locale in GOH_TRANSLATION_LOCALES:
        locale_map: dict[tuple[str, str], str] = {}
        for context in GOH_TRANSLATION_CONTEXTS:
            for msgid in msgids:
                locale_map[(context, msgid)] = msgid
        translations[locale] = locale_map
    return translations


GOH_TRANSLATION_OVERRIDES = _build_translation_overrides()


def _part_keys_for_role(role_key: str, family_key: str = "GENERIC") -> tuple[str, ...]:
    template_map = GOH_TEMPLATE_ROLE_PART_KEYS.get(family_key, GOH_TEMPLATE_ROLE_PART_KEYS["GENERIC"])
    return template_map.get(role_key, GOH_ROLE_PART_KEYS.get(role_key, GOH_ROLE_PART_KEYS["visual"]))


def _part_items_for_role(role_key: str, family_key: str = "GENERIC") -> list[tuple[str, str, str]]:
    items: list[tuple[str, str, str]] = []
    for key in _part_keys_for_role(role_key, family_key):
        preset = GOH_PART_PRESET_MAP[key]
        items.append((preset.key, preset.label, preset.description))
    return items


def _resolve_part_preset(role_key: str, part_key: str, family_key: str = "GENERIC") -> GOHPartPreset:
    allowed = _part_keys_for_role(role_key, family_key)
    if part_key in allowed:
        return GOH_PART_PRESET_MAP[part_key]
    return GOH_PART_PRESET_MAP[allowed[0]]


def _goh_part_items(settings, _context):
    role_key = getattr(settings, "role", "visual")
    family_key = getattr(settings, "template_family", "GENERIC")
    return _part_items_for_role(role_key, family_key)


def _goh_role_updated(settings, _context) -> None:
    allowed = _part_keys_for_role(getattr(settings, "role", "visual"), getattr(settings, "template_family", "GENERIC"))
    if getattr(settings, "part", "") not in allowed:
        settings.part = allowed[0]


def _goh_template_updated(settings, _context) -> None:
    _goh_role_updated(settings, _context)
